### ISSUE TITLE
Page is not saved on click anymore

### ISSUE THREAD

**Issue by TheCapsLock** [AaronLenoir/SendToArchive#6]
Hi, thanks a lot for this useful extension.

I encounter an issue about a week or so: when clicking the icon on firefox toolbar, it opens a tab at ```https://web.archive.org/save/<my url>``` where "my url" is the website I want to add to the wayback machine. If we look at network inspector we see we get a 400 (bad request) status code in response to this GET request call.

In the past that was working, but nowadays it only gives a blank page; I have to browse to ```https://web.archive.org/save/``` and enter manually "my url" in the input field of the form of the page. Doing so the page is saved (wayback machine uses a POST request here)

**Comment by AaronLenoir** [comment]
Hello

Thanks for the feedback. May I ask which browser you are using?

I've had the same issue before, clearing my browser cache for archive.org seemed to have solved it. I hadn't looked further into what was happening.

I will see if I can look into the way it works with POST, but not sure how I will be able to fit this into the add-in, since I'm trying to keep it as simple as possible. I was working under the assumption that manually putting that URL there and doing it via the extension would be identical. So I'm surprised the behavior is different. Very interesting.

Thanks!
Aaron

**Comment by TheCapsLock** [comment]
I was using Firefox 74.

Thanks for the tip of clearing the browser cache:  it worked ! (I used History, searched for web.archive.org, told firefox to forget the website)
